In [1]:
import pandas as pd
import requests

### 1. Items

In [2]:
base_url = 'https://python.zgulde.net/api/v1/items'

In [3]:
data = requests.get(base_url).json()

In [4]:
curr_page = data['payload']['page']
max_page = data['payload']['max_page']
next_page = data['payload']['next_page']

In [5]:
new_data = requests.get(base_url+'?page='+next_page[-1]).json()
new_data['payload']['page']

2

In [6]:
base_url = 'https://python.zgulde.net/api/v1/items'
data = requests.get(base_url).json()

curr_page = data['payload']['page']
max_page = data['payload']['max_page']
next_page = data['payload']['next_page']

items_list = requests.get(base_url).json()['payload']['items']

while curr_page <= max_page:
    new_data = requests.get(base_url+'?page='+next_page[-1]).json()['payload']
    for store in new_data['items']:
        items_list.append(store)
    if curr_page < max_page:
        next_page = new_data['next_page']
        curr_page = requests.get(base_url+'?page='+next_page[-1]).json()['payload']['page']
        continue
    else:
        break

items = pd.DataFrame(items_list)
items

,item_brand,item_id,item_name,item_price,item_upc12,item_upc14
0,Riceland,1,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,Caress,2,Caress Velvet Bliss Ultra Silkening Beauty Bar...,6.44,11111065925,11111065925
2,Earths Best,3,Earths Best Organic Fruit Yogurt Smoothie Mixe...,2.43,23923330139,23923330139
3,Boars Head,4,Boars Head Sliced White American Cheese - 120 Ct,3.14,208528800007,208528800007
4,Back To Nature,5,Back To Nature Gluten Free White Cheddar Rice ...,2.61,759283100036,759283100036
5,Sally Hansen,6,Sally Hansen Nail Color Magnetic 903 Silver El...,6.93,74170388732,74170388732
6,Twinings Of London,7,Twinings Of London Classics Lady Grey Tea - 20 Ct,9.64,70177154004,70177154004
7,Lea & Perrins,8,Lea & Perrins Marinade In-a-bag Cracked Pepper...,1.68,51600080015,51600080015
8,Van De Kamps,9,Van De Kamps Fillets Beer Battered - 10 Ct,1.79,19600923015,19600923015
9,Ahold,10,Ahold Cocoa Almonds,3.17,688267141676,688267141676
10,Honest Tea,11,Honest Tea Peach White Tea,3.93,657622604842,657622604842
11,Mueller,12,Mueller Sport Care Basic Support Level Medium ...,8.40,74676640211,74676640211
12,Garnier Nutritioniste,13,Garnier Nutritioniste Moisture Rescue Fresh Cl...,6.47,603084234561,603084234561
13,Pamprin,14,Pamprin Maximum Strength Multi-symptom Menstru...,7.54,41167300121,41167300121
14,Suave,15,Suave Naturals Moisturizing Body Wash Creamy T...,9.11,79400847201,79400847201
15,Burts Bees,16,Burts Bees Daily Moisturizing Cream Sensitive,5.17,792850014008,792850014008
16,Ducal,17,Ducal Refried Red Beans,1.16,88313590791,88313590791
17,Scotch,18,Scotch Removable Clear Mounting Squares - 35 Ct,4.39,21200725340,21200725340
18,Careone,19,Careone Family Comb Set - 8 Ct,0.74,41520035646,41520035646
19,Usda Produce,20,Plums Black,5.62,204040000000,204040000000
20,Doctors Best,21,Doctors Best Best Curcumin C3 Complex 1000mg T...,8.09,753950001954,753950001954
21,Betty Crocker,22,Betty Crocker Twin Pack Real Potatoes Scallope...,7.31,16000288829,16000288829
22,Reese,23,Reese Mandarin Oranges Segments In Light Syrup,1.78,70670009658,70670009658
23,Smart Living,24,Smart Living Charcoal Lighter Fluid,5.34,688267084225,688267084225
24,Hood,25,Hood Latte Iced Coffee Drink Vanilla Latte,2.43,44100117428,44100117428
25,Triaminic,26,Triaminic Syrup Night Time Cold & Cough Grape 4oz,0.98,300436344045,300436344045
26,Morton,27,Morton Kosher Salt Coarse,6.01,24600017008,24600017008
27,Usda Produce,28,Guava,7.52,719175900007,719175900007
28,Heinz,29,Heinz Tomato Ketchup - 2 Ct,8.65,13000001038,13000001038
29,Petmate,30,Petmate Booda Bones Steak Bacon & Chicken Flav...,8.39,723503568678,723503568678
30,Zhenas Gypsy Tea,31,Zhenas Gypsy Tea Herbal Red Tea Sachets Fire L...,4.21,652790100226,652790100226
31,Barefoot,32,Barefoot Pinot Grigio 187,0.68,8500004528,8500004528
32,The First Years,33,Tomy The First Years Gumdrop Orthodontic Pacif...,6.52,71463060078,71463060078
33,Halls,34,Halls Menthol Cough Suppresant/oral Anesthetic...,4.17,312546628694,312546628694
34,Natures Way,35,Natures Way Forskohlii - 60 Ct,5.19,33674100066,33674100066
35,Deerfields Gluten Free,36,Rice Bran Gluten Free Dinner Rolls Plain,7.95,610358991525,610358991525
36,Nakano,37,Nakano Seasoned Rice Vinegar Original,9.59,73575295003,73575295003
37,Sundown Naturals,38,Sundown Naturals Essential Electrolytes Tropic...,3.45,30768540548,30768540548
38,Munchies,39,Munchies Sandwich Crackers Cheddar Cheese On G...,9.02,28400029254,28400029254
39,Amys,40,Amys Light & Lean Spaghetti Italiano,0.60,42272008063,42272008063
40,P.f. Changs,41,P.f. Changs Home Menu Meal For Two Beef With B...,5.62,31000670016,31000670016
41,Moms Best Naturals,42,Moms Best Naturals Cereal Toasted Cinnamon Squ...,2.97,883978129115,883978129115
42,Ferrara,43,Ferrara Vanilla Syrup,8.40,71403000379,71403000379
43,Elmers,44,Elmers Board Mate Dual Tip Glue Pen,7.06,26000001403,26000001403
44,Kelloggs,45,Kelloggs Disney Pixar Cars 2 Cereal,4.40,38000542237,38000542237
45,Mama Marys,46,Pizza Sauce,4.65,35457770664,35457770664
46,Bear Naked,47,Bear Naked Fit Almond Crisp 100 Percent Natura...,7.38,884623708976,884623708976
47,Dove,48,Dove Men + Care Antiperspirant Deodorant Cool ...,3.72,79400271631,79400271631
48,Easy-off,49,Easy-off Oven Cleaner Lemon Scent,9.54,62338879772,62338879772
49,Choice,50,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221

### 2. Stores

In [7]:
base_url = 'https://python.zgulde.net/api/v1/stores'

store_list = requests.get(base_url).json()['payload']['stores']

stores = pd.DataFrame(store_list)
stores

             store_address   store_city  store_id store_state store_zipcode
0   12125 Alamo Ranch Pkwy  San Antonio         1          TX         78253
1         9255 FM 471 West  San Antonio         2          TX         78251
2  2118 Fredericksburg Rdj  San Antonio         3          TX         78201
3          516 S Flores St  San Antonio         4          TX         78204
4          1520 Austin Hwy  San Antonio         5          TX         78218
5       1015 S WW White Rd  San Antonio         6          TX         78220
6   12018 Perrin Beitel Rd  San Antonio         7          TX         78217
7      15000 San Pedro Ave  San Antonio         8          TX         78232
8       735 SW Military Dr  San Antonio         9          TX         78221
9     8503 NW Military Hwy  San Antonio        10          TX         78231

### 3. Sales

In [8]:
requests.get(base_url+'?page=183').json()['payload'].keys()

dict_keys(['max_page', 'next_page', 'page', 'previous_page', 'stores'])

In [12]:
base_url = 'https://python.zgulde.net/api/v1/sales'
data = requests.get(base_url).json()

curr_page = data['payload']['page']
max_page = data['payload']['max_page']
next_page = data['payload']['next_page']

sales_list = requests.get(base_url).json()['payload']['sales']
while curr_page < max_page:
    next_page_url = base_url+'?page='+str((curr_page+1))
    new_data = requests.get(next_page_url).json()['payload']
    curr_page = requests.get(next_page_url).json()['payload']['page']
    print(f'Reading page: {curr_page}')
    sales_list.extend(new_data['sales'])

sales = pd.DataFrame(sales_list)
sales

Reading page: 2
Reading page: 3
Reading page: 4
Reading page: 5
Reading page: 6
Reading page: 7
Reading page: 8
Reading page: 9
Reading page: 10
Reading page: 11
Reading page: 12
Reading page: 13
Reading page: 14
Reading page: 15
Reading page: 16
Reading page: 17
Reading page: 18
Reading page: 19
Reading page: 20
Reading page: 21
Reading page: 22
Reading page: 23
Reading page: 24
Reading page: 25
Reading page: 26
Reading page: 27
Reading page: 28
Reading page: 29
Reading page: 30
Reading page: 31
Reading page: 32
Reading page: 33
Reading page: 34
Reading page: 35
Reading page: 36
Reading page: 37
Reading page: 38
Reading page: 39
Reading page: 40
Reading page: 41
Reading page: 42
Reading page: 43
Reading page: 44
Reading page: 45
Reading page: 46
Reading page: 47
Reading page: 48
Reading page: 49
Reading page: 50
Reading page: 51
Reading page: 52
Reading page: 53
Reading page: 54
Reading page: 55
Reading page: 56
Reading page: 57
Reading page: 58
Reading page: 59
Reading page: 60
Reading page: 61
Reading page: 62
Reading page: 63
Reading page: 64
Reading page: 65
Reading page: 66
Reading page: 67
Reading page: 68
Reading page: 69
Reading page: 70
Reading page: 71
Reading page: 72
Reading page: 73
Reading page: 74
Reading page: 75
Reading page: 76
Reading page: 77
Reading page: 78
Reading page: 79
Reading page: 80
Reading page: 81
Reading page: 82
Reading page: 83
Reading page: 84
Reading page: 85
Reading page: 86
Reading page: 87
Reading page: 88
Reading page: 89
Reading page: 90
Reading page: 91
Reading page: 92
Reading page: 93
Reading page: 94
Reading page: 95
Reading page: 96
Reading page: 97
Reading page: 98
Reading page: 99
Reading page: 100
Reading page: 101
Reading page: 102
Reading page: 103
Reading page: 104
Reading page: 105
Reading page: 106
Reading page: 107
Reading page: 108
Reading page: 109
Reading page: 110
Reading page: 111
Reading page: 112
Reading page: 113
Reading page: 114
Reading page: 115
Reading page: 116
Reading page: 117
Reading page: 118
Reading page: 119
Reading page: 120
Reading page: 121
Reading page: 122
Reading page: 123
Reading page: 124
Reading page: 125
Reading page: 126
Reading page: 127
Reading page: 128
Reading page: 129
Reading page: 130
Reading page: 131
Reading page: 132
Reading page: 133
Reading page: 134
Reading page: 135
Reading page: 136
Reading page: 137
Reading page: 138
Reading page: 139
Reading page: 140
Reading page: 141
Reading page: 142
Reading page: 143
Reading page: 144
Reading page: 145
Reading page: 146
Reading page: 147
Reading page: 148
Reading page: 149
Reading page: 150
Reading page: 151
Reading page: 152
Reading page: 153
Reading page: 154
Reading page: 155
Reading page: 156
Reading page: 157
Reading page: 158
Reading page: 159
Reading page: 160
Reading page: 161
Reading page: 162
Reading page: 163
Reading page: 164
Reading page: 165
Reading page: 166
Reading page: 167
Reading page: 168
Reading page: 169
Reading page: 170
Reading page: 171
Reading page: 172
Reading page: 173
Reading page: 174
Reading page: 175
Reading page: 176
Reading page: 177
Reading page: 178
Reading page: 179
Reading page: 180
Reading page: 181
Reading page: 182
Reading page: 183

        item  sale_amount                      sale_date  sale_id  store
0          1         13.0  Tue, 01 Jan 2013 00:00:00 GMT        1      1
1          1         11.0  Wed, 02 Jan 2013 00:00:00 GMT        2      1
2          1         14.0  Thu, 03 Jan 2013 00:00:00 GMT        3      1
3          1         13.0  Fri, 04 Jan 2013 00:00:00 GMT        4      1
4          1         10.0  Sat, 05 Jan 2013 00:00:00 GMT        5      1
...      ...          ...                            ...      ...    ...
912995    50         63.0  Wed, 27 Dec 2017 00:00:00 GMT   912996     10
912996    50         59.0  Thu, 28 Dec 2017 00:00:00 GMT   912997     10
912997    50         74.0  Fri, 29 Dec 2017 00:00:00 GMT   912998     10
912998    50         62.0  Sat, 30 Dec 2017 00:00:00 GMT   912999     10
912999    50         82.0  Sun, 31 Dec 2017 00:00:00 GMT   913000     10

[913000 rows x 5 columns]

### 4. Save them to CSVs

In [13]:
items.to_csv('items.csv')

In [14]:
stores.to_csv('stores.csv')

In [15]:
sales.to_csv('sales.csv')

### 5. Combine them

In [16]:
sales.columns.tolist()

['item', 'sale_amount', 'sale_date', 'sale_id', 'store']

In [17]:
sales.columns = ['item_id', 'sale_amount', 'sale_date', 'sale_id', 'store_id']

In [18]:
df = pd.merge(sales, stores, on='store_id', how='left')

In [19]:
df = pd.merge(df, items, on='item_id', how='left')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 913000 entries, 0 to 912999
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item_id        913000 non-null  int64
 1   sale_amount    913000 non-null  float64
 2   sale_date      913000 non-null  object
 3   sale_id        913000 non-null  int64
 4   store_id       913000 non-null  int64
 5   store_address  913000 non-null  object
 6   store_city     913000 non-null  object
 7   store_state    913000 non-null  object
 8   store_zipcode  913000 non-null  object
 9   item_brand     913000 non-null  object
 10  item_name      913000 non-null  object
 11  item_price     913000 non-null  float64
 12  item_upc12     913000 non-null  object
 13  item_upc14     913000 non-null  object
dtypes: float64(2), int64(3), object(9)
memory usage: 104.5+ MB

### 6. German power data

In [23]:
url = 'https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv'
power = pd.read_csv(url)

In [24]:
power.to_csv('power_systems.csv')

### 7. Make and test out acquire.py

In [25]:
import acquire

In [26]:
df = acquire.get_combined_csv()

In [27]:
power = acquire.get_power_data()

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 913000 entries, 0 to 912999
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item_id        913000 non-null  int64
 1   sale_amount    913000 non-null  float64
 2   sale_date      913000 non-null  object
 3   sale_id        913000 non-null  int64
 4   store_id       913000 non-null  int64
 5   store_address  913000 non-null  object
 6   store_city     913000 non-null  object
 7   store_state    913000 non-null  object
 8   store_zipcode  913000 non-null  int64
 9   item_brand     913000 non-null  object
 10  item_name      913000 non-null  object
 11  item_price     913000 non-null  float64
 12  item_upc12     913000 non-null  int64
 13  item_upc14     913000 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 104.5+ MB

In [29]:
power.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         4383 non-null   object
 1   Consumption  4383 non-null   float64
 2   Wind         2920 non-null   float64
 3   Solar        2188 non-null   float64
 4   Wind+Solar   2187 non-null   float64
dtypes: float64(4), object(1)
memory usage: 171.3+ KB